title: turtleblog
description: No turtles were harmed during coding.
permalink: /posts/:name:output_ext

header_pages:
  - about.markdown

style: light

plugins:
  - jekyll-feed
  - jekyll-spaceship

jekyll-spaceship:
  processors:
    - mathjax-processor
    - mermaid-processor
  mermaid-processor:
    syntax:
      code: 'mermaid'
    config:
      theme: neutral
    src: https://mermaid.ink/img/
