title: turtleblog
email: scturtle@gmail.com
description: No turtles were harmed during coding.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: scturtle
github_username:  scturtle
permalink: /posts/:name:output_ext

theme: minima
plugins:
  - jekyll-feed
  - jekyll-spaceship

jekyll-spaceship:
  processors:
    - mathjax-processor
