title: turtleblog
description: No turtles were harmed during coding.
permalink: /posts/:name:output_ext

header_pages:
  - about.markdown

style: light

plugins:
  - jekyll-feed
  - jekyll-spaceship

jekyll-spaceship:
  processors:
    - mathjax-processor
