title: turtleblog
author:
  name: scturtle
  twitter: scturtle
  email: scturtle@gmail.com
description: No turtles were harmed during coding.
permalink: /posts/:name:output_ext

theme: minima
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    github: scturtle
    twitter: scturtle
    telegram: scturtle

plugins:
  - jekyll-feed
  - jekyll-spaceship
  - jekyll-remote-theme

jekyll-spaceship:
  processors:
    - mathjax-processor
